version: '3.9'
services:
  postgresql:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: scrapper
      PGDATA: /data/postgres
    volumes:
      - scrapper-postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=changeme
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbit-mq:
    image: rabbitmq:3-management
    volumes:
      - rabbit-mq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  scrapper-postgres:
    { }
  rabbit-mq:
    { }
