global:
  scrape_interval:     15s
scrape_configs:
  - job_name: 'scrapper'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]

  - job_name: 'bot'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]
