/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends UpdatableRecordImpl<LinkRecord> implements Record9<Long, String, Long, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.id</code>.
     */
    public void setId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.id</code>.
     */
    @NotNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 2048)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.link.tg_id</code>.
     */
    public void setTgId(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.tg_id</code>.
     */
    @Nullable
    public Long getTgId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.link.checked_at</code>.
     */
    public void setCheckedAt(@Nullable LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.link.checked_at</code>.
     */
    @Nullable
    public LocalDateTime getCheckedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.link.update_at</code>.
     */
    public void setUpdateAt(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.link.update_at</code>.
     */
    @Nullable
    public LocalDateTime getUpdateAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.link.open_issues_count</code>.
     */
    public void setOpenIssuesCount(@Nullable Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.link.open_issues_count</code>.
     */
    @Nullable
    public Integer getOpenIssuesCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.link.forks_count</code>.
     */
    public void setForksCount(@Nullable Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.link.forks_count</code>.
     */
    @Nullable
    public Integer getForksCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.link.answer_count</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.link.answer_count</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.link.comment_count</code>.
     */
    public void setCommentCount(@Nullable Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.link.comment_count</code>.
     */
    @Nullable
    public Integer getCommentCount() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row9<Long, String, Long, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row9<Long, String, Long, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Link.LINK.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Link.LINK.URL;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Link.LINK.TG_ID;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field4() {
        return Link.LINK.CHECKED_AT;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Link.LINK.UPDATE_AT;
    }

    @Override
    @NotNull
    public Field<Integer> field6() {
        return Link.LINK.OPEN_ISSUES_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field7() {
        return Link.LINK.FORKS_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field8() {
        return Link.LINK.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Field<Integer> field9() {
        return Link.LINK.COMMENT_COUNT;
    }

    @Override
    @NotNull
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @Nullable
    public Long component3() {
        return getTgId();
    }

    @Override
    @Nullable
    public LocalDateTime component4() {
        return getCheckedAt();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getUpdateAt();
    }

    @Override
    @Nullable
    public Integer component6() {
        return getOpenIssuesCount();
    }

    @Override
    @Nullable
    public Integer component7() {
        return getForksCount();
    }

    @Override
    @Nullable
    public Integer component8() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer component9() {
        return getCommentCount();
    }

    @Override
    @NotNull
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @Nullable
    public Long value3() {
        return getTgId();
    }

    @Override
    @Nullable
    public LocalDateTime value4() {
        return getCheckedAt();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getUpdateAt();
    }

    @Override
    @Nullable
    public Integer value6() {
        return getOpenIssuesCount();
    }

    @Override
    @Nullable
    public Integer value7() {
        return getForksCount();
    }

    @Override
    @Nullable
    public Integer value8() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Integer value9() {
        return getCommentCount();
    }

    @Override
    @NotNull
    public LinkRecord value1(@NotNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value3(@Nullable Long value) {
        setTgId(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value4(@Nullable LocalDateTime value) {
        setCheckedAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value5(@Nullable LocalDateTime value) {
        setUpdateAt(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value6(@Nullable Integer value) {
        setOpenIssuesCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value7(@Nullable Integer value) {
        setForksCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value8(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord value9(@Nullable Integer value) {
        setCommentCount(value);
        return this;
    }

    @Override
    @NotNull
    public LinkRecord values(@NotNull Long value1, @NotNull String value2, @Nullable Long value3, @Nullable LocalDateTime value4, @Nullable LocalDateTime value5, @Nullable Integer value6, @Nullable Integer value7, @Nullable Integer value8, @Nullable Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    @ConstructorProperties({ "id", "url", "tgId", "checkedAt", "updateAt", "openIssuesCount", "forksCount", "answerCount", "commentCount" })
    public LinkRecord(@NotNull Long id, @NotNull String url, @Nullable Long tgId, @Nullable LocalDateTime checkedAt, @Nullable LocalDateTime updateAt, @Nullable Integer openIssuesCount, @Nullable Integer forksCount, @Nullable Integer answerCount, @Nullable Integer commentCount) {
        super(Link.LINK);

        setId(id);
        setUrl(url);
        setTgId(tgId);
        setCheckedAt(checkedAt);
        setUpdateAt(updateAt);
        setOpenIssuesCount(openIssuesCount);
        setForksCount(forksCount);
        setAnswerCount(answerCount);
        setCommentCount(commentCount);
    }
}
