name: bot
on:
  push:
    paths:
      - 'bot/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: Setup Java SDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'amazoncorretto'
            cache: maven
        - name: Build with Maven
          run: mvn package -pl bot -am
        - name: Build bot image
          run: docker build -f bot.Dockerfile -t bot.

