name: scrapper
on:
  push:
    paths:
      - 'scrapper/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper
  AUTHOR: paegorofff

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Java SDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn package -pl scrapper -am

      - name: Build scrapper image
        run: docker build -f scrapper.Dockerfile -t ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE_NAME }}:latest .

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.AUTHOR }}/${{ env.IMAGE_NAME }}:latest

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: maven

      - name: Run Checkstyle
        run: mvn -pl scrapper -am checkstyle:check
